server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE